### ISSUE TITLE
Only show subject name when one is provided in the credential data

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/web-verifier-plus#100]
Currently it appears that Subject Name is displaying even if one isn't provided.

**Comment by lautom36** [comment]
[pr](https://github.com/digitalcredentials/web-verifier-plus/pull/105)

**Comment by kayaelle** [comment]
Looks good.

**Comment by alexfigtree** [comment]
Keeping open until after deployment

**Comment by alexfigtree** [comment]
Deployed on 3/18/24
