### ISSUE TITLE
Change Subject Name to Issued To

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/web-verifier-plus#104]
Subject Name is used as the label for when there is a credentialSubject.name. Please change this label to "Issued To".

**Comment by lautom36** [comment]
[pr](https://github.com/digitalcredentials/web-verifier-plus/pull/105)

**Comment by kayaelle** [comment]
Looks good.

**Comment by alexfigtree** [comment]
Deployed on 3/18/24.
