### ISSUE TITLE
Misspelled alt text for the DCC logo in the footer

### ISSUE THREAD

**Issue by ThinkBrandonThink** [digitalcredentials/web-verifier-plus#112]
"Credentials" is misspelled in the alt text for the DCC logo in the footer.

**Comment by kayaelle** [comment]
PR https://github.com/digitalcredentials/web-verifier-plus/pull/133

**Comment by alexfigtree** [comment]
PR #133 Merged, this ticket moving to Release Ready.

**Comment by alexfigtree** [comment]
Tested, looks good, closing
