### ISSUE TITLE
Add Auto-restart

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/web-verifier-plus#126]
Add nodemon or a library like this that will restart VerfifierPlus automatically if it goes down. 

This issue is a blocker for https://github.com/digitalcredentials/learner-credential-wallet/issues/604

**Comment by alexfigtree** [comment]
Blocker for https://github.com/digitalcredentials/learner-credential-wallet/issues/604

**Comment by jchartrand** [comment]
https://github.com/digitalcredentials/web-verifier-plus/pull/130

**Comment by alexfigtree** [comment]
Issue completed, moving to Done
