### ISSUE TITLE
Fix verification result UI

### ISSUE THREAD

**Issue by jchartrand** [digitalcredentials/web-verifier-plus#136]
Right now Verifier+ only shows the checkboxes if all are valid - or if the credential has been revoked (and everything else is valid).
For any other case (expired, missing issuer) it shows a generic error: "There was an error verifing this credential. More Info" and  that 'More Info' link doesn't go anywhere.
So, we could fix it so that:
1. If the signature is invalid then:
	- All bets are off - we can't say anything about any of the checks (revocation, issuer, expiry) because they may have been tampered with, and we shouldn't even show them.
	- So just show a single error saying "The signature doesn't match the content of the credential. No change, however minor, can be made to the content."
2. For any other combination of checks, show the checkboxes, with checkmarks or x's as appropriate.

**Comment by jchartrand** [comment]
From @kayaelle 
For the signature error message, can we try some options that are for non-technical audiences? Maybe a simpler message followed up with the more detailed explanatory message?

**Comment by jchartrand** [comment]
For context, this is what a fully verified credential looks like in V+ now:

<img width="988" alt="image" src="https://github.com/user-attachments/assets/52d82dd1-6ac3-4886-8953-7a71ee9ec768">

And this is how it looks when a credential's signature is invalid, or the credential has expired, or the issuer isn't in the registry:

![image](https://github.com/user-attachments/assets/75880456-c6ff-4344-90a7-1db01cd1f1b9)

**Comment by jchartrand** [comment]
Suggested error message from @gwalsh311 for an invalid signature:

 "This credential cannot be verified. Note that the JSON code is sensitive to changes in code text including spaces and characters. Please ensure you have input the correct code."

**Comment by jchartrand** [comment]
Fixed with PR https://github.com/digitalcredentials/web-verifier-plus/pull/131 which also adds VC2 and bit string status support.

**Comment by alexfigtree** [comment]
Done and deployed 10/3/24
