### ISSUE TITLE
Revoked credentials don't have log in in result from verify api.

### ISSUE THREAD

**Issue by lautom36** [digitalcredentials/web-verifier-plus#24]
The last two credentials in https://github.com/digitalcredentials/docs/issues/10 which should be revoked don't have a log in their result once they have been verified.

**Comment by kayaelle** [comment]
@lautom36 is this something we should still fix?

**Comment by lautom36** [comment]
I haven't seen this behavior with any of the new credentials, so for now it doesn't seem like a major issue.
