### ISSUE TITLE
VerifierPlus does not recognize new issuers in any registry

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/web-verifier-plus#52]
Issuer DIDs are hardcoded into VerifierPlus.

https://github.com/digitalcredentials/web-verifier-plus/blob/main/data/issuerDid.ts

If a new issuer is added to one of the DCC registries, VerifierPlus does not recognize the did.

**Comment by kayaelle** [comment]
Related to [https://github.com/digitalcredentials/verifier/issues/3](https://github.com/digitalcredentials/verifier/issues/3)

**Comment by kayaelle** [comment]
Moving to ready for review.

**Comment by alexfigtree** [comment]
Prioritizing https://github.com/digitalcredentials/web-verifier-plus/issues/141 over this ticket, closing
