### ISSUE TITLE
VerifierPlus does not report if a did is not found in a registry

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/web-verifier-plus#53]
https://github.com/digitalcredentials/web-verifier-plus/blob/838cd0023cf2cda0eda033d5e5427596021bbd61/lib/validate.ts#L58-L59

```
  if (!registries.issuerDid.isInRegistry(issuerDid)) {
    throw new Error(CredentialErrorTypes.DidNotInRegistry);
  }
```

Instead of showing an error the UI is stuck at "Verifying..."

**Comment by lautom36** [comment]
This issue is resolved with the fix from [#52](https://github.com/digitalcredentials/web-verifier-plus/issues/52)

**Comment by kayaelle** [comment]
@lautom36 - please see #52 - seems to be related.

**Comment by kayaelle** [comment]
Going to close this because we are changing how we search the registries related to issue: #3
