### ISSUE TITLE
Credentials showing as Not Verified in VerifierPlus, previously verified

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/web-verifier-plus#72]
I'm not sure if this is a VerifierPlus issue, a LCW issue or credential creation issue.

I think it may have something to do with the change to the security loader or other work related to Open edX's integration of DCC libraries. I suspect it's also similar to the issue Stuart reported to Dmitri in slack. But those are both only guesses.

Credentials created (baked) on April 14 or June 29 using James' test-signer show as verified in the LCW v2.0.0-Build 56 under iOS (aka the last version of LCW uploaded to the Apple App Store) but show as Not Verified on public links on https://verifierplus.org.

Credentials issued by CU (as a test, but they should be the same as the live BA digital diplomas CU issued to graduates) using sign-and-verify also return Not Verified via public links in VerifierPlus.

VC baked on 6/29/23 using test-signer:
[validBadge-aseptic-technique.zip](https://github.com/digitalcredentials/web-verifier-plus/files/11906805/validBadge-aseptic-technique.zip)

VC baked on 4/14/23 using test-signer:
[valid-dcc-demo.zip](https://github.com/digitalcredentials/web-verifier-plus/files/11906819/valid-dcc-demo.zip)

VC issued from sign-and-verify by CU:
https://lcw.app/request.html?issuer=https://connect.collegeunbound.edu&vc_request_url=https://connect.collegeunbound.edu/request/credential&challenge=VOclS8ZiMs&auth_type=bearer

VerifierPlus used to verify the VC on 4/24/23:
<img width="504" alt="Screen Shot 2023-04-21 at 1 57 36 PM" src="https://github.com/digitalcredentials/web-verifier-plus/assets/752326/78898bc9-c365-4bcf-bfb9-8f0663fedab0">

VerifierPlus reports Not Verified and Invalid Signature of the same VC on 6/29/23:
<img width="396" alt="Screen Shot 2023-06-29 at 7 10 54 AM" src="https://github.com/digitalcredentials/web-verifier-plus/assets/752326/e6d68c6d-dfd5-42d1-9085-2bc0e2f344b4">

**Comment by bmuramatsu** [comment]
Previously created credentials verify as they had previously.

**Comment by bmuramatsu** [comment]
> Yeah, the reason I think we should recommend that the SJCC and CU credentials get re-issued, is that this fix is only for wallets and verifiers using our (DCC) libraries. Other implementations will show those VCs as not verified. (Due to 1EdTech OBv3 WG changing the contents of its context/schema without updating the context URL).

To @dmitrizagidulin's point about multiple contexts... we're at the start of OBv3 implementation so we might expect implementers to keep updating to the latest context, but as time proceeds wouldn't we expect multiple versions of the contexts we support to be in the wild? 

Thus, shouldn't we:
- Need to recommend other implementers support multiple contexts, especially for OBv3, and presumably VC v2 when it is finalized?
- Continue to support multiple contexts?
- Consider whether we keep a copy of the contexts we support directly and do a diff on them with the one that's listed to check for stealth changes that might break something?

**Comment by kayaelle** [comment]
Will create follow-up issue on display based on contexts. There are two other badge display issues that reference similar issues:

[https://github.com/digitalcredentials/web-verifier-plus/issues/85](https://github.com/digitalcredentials/web-verifier-plus/issues/85)
`https://github.com/digitalcredentials/learner-credential-wallet/issues/460`
