### ISSUE TITLE
"View on Github" link doesn't go to github

### ISSUE THREAD

**Issue by stuartf** [digitalcredentials/web-verifier-plus#73]
This link seems to be pointing back to verifierplus.org or `/` or something as it doesn't result in navigating away from the page.

**Comment by kayaelle** [comment]
Made the repo public! Thanks @bmuramatsu

**Comment by kayaelle** [comment]
re-opening - we need to add the url to the github link.

**Comment by kayaelle** [comment]
This can be closed.
