### ISSUE TITLE
Unhandled Runtime Error 

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/web-verifier-plus#81]
Verified credential shared from LCW resulted in error below:

<img width="579" alt="Screen Shot 2023-07-17 at 4 11 19 PM" src="https://github.com/digitalcredentials/web-verifier-plus/assets/206059/f5f570b2-2f6c-4a06-9a41-b17b7f7f106c">

Credential data:

{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://purl.imsglobal.org/spec/ob/v3p0/context.json",
    "https://w3id.org/security/suites/ed25519-2020/v1"
  ],
  "type": [
    "VerifiableCredential",
    "OpenBadgeCredential"
  ],
  "credentialSubject": {
    "type": [
      "AchievementSubject"
    ],
    "achievement": {
      "type": [
        "Achievement"
      ],
      "achievementType": "Badge",
      "criteria": {
        "type": "Criteria",
        "narrative": "This credential has the following criteria - achievementType Badge, subjectName, exists in issuer registry, not revoked, not expired, linked issuer image."
      },
      "description": "This is a sample credential issued by the Digital Credentials Consortium to demonstrate the functionality of Verifiable Credentials for wallets and verifiers.",
      "id": "urn:uuid:bd6d9316-f7ae-4073-a1e5-2f7f5bd22922",
      "image": {
        "type": "Image",
        "id": "https://user-images.githubusercontent.com/752326/214947713-15826a3a-b5ac-4fba-8d4a-884b60cb7157.png"
      },
      "name": "Badge"
    },
    "name": "Ian Malcom"
  },
  "expirationDate": "2025-12-20T22:42:27.438Z",
  "id": "https://raw.githubusercontent.com/jchartrand/dcc-test-creds/main/validBadge/validBadge.json",
  "issuanceDate": "2021-01-19T18:22:34.772810+00:00",
  "issuer": {
    "type": [
      "Profile"
    ],
    "id": "did:key:z6Mkmjp1vQNev9wYjRA9DqnXwKRuDTb85UGhcjK1FTWrdu6X",
    "image": "https://user-images.githubusercontent.com/947005/133544904-29d6139d-2e7b-4fe2-b6e9-7d1022bb6a45.png",
    "name": "Digital Credentials Consortium Test Issuer",
    "url": "https://www.dcconsortium.org/"
  },
  "name": "DCC Test Credential",
  "proof": {
    "type": "Ed25519Signature2020",
    "created": "2023-02-18T13:50:47Z",
    "proofPurpose": "assertionMethod",
    "proofValue": "z2dHapVfXRJjxw1a6TorMHmDxsa6tU91jgUYZ36Z7DeiEKg53zncgiHid4USP8U2N2wHcVrfBBoPbovrPhNNRmfJ",
    "verificationMethod": "did:key:z6Mkmjp1vQNev9wYjRA9DqnXwKRuDTb85UGhcjK1FTWrdu6X#z6Mkmjp1vQNev9wYjRA9DqnXwKRuDTb85UGhcjK1FTWrdu6X"
  }
}

**Comment by lautom36** [comment]
I'm having issues recreating this error, I can get an error with the did not being in the registry, but I can't get that syntax error to show up. When you got that issue, were you using ios?

**Comment by kayaelle** [comment]
I was using iOS. Will close. Thanks!
