### ISSUE TITLE
Add Markdown support for criteria.narrative

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/web-verifier-plus#84]
Let's add sanitized markdown for criteria.narrative:

Criteria.narrative: https://1edtech.github.io/openbadges-specification/ob_v3p0.html#org.1edtech.ob.v3p0.criteria.class

**Comment by bmuramatsu** [comment]
Using BCSI test badge with unordered list, displays as expected on iOS Safari and Android Chrome.

(Should be tested with all supported markdown elements.)

**Comment by kayaelle** [comment]
Follow-up issue created.
