### ISSUE TITLE
Open Badges 3.0 Display

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/web-verifier-plus#85]
This issue explains which Open Badges 3.0 fields the VerifierPlus should display if a Verifiable Credential also contains the type: "AchievementCredential" or "OpenBadgeCredential".  The list of fields begins here:

https://1edtech.github.io/openbadges-specification/ob_v3p0.html#achievementcredential

Required properties are bolded. Otherwise, display only if the value exists.

- AchievementCredential.name (currently called "title" in the LCW) **Required** 
- Achievement.image (https://1edtech.github.io/openbadges-specification/ob_v3p0.html#achievement) - already being displayed

Issuer:
Issuer Information (https://1edtech.github.io/openbadges-specification/ob_v3p0.html#org.1edtech.ob.v3p0.profile.class)

- profile.name (**Required** )
- If exists: profile.image, profile.url, profile.address (location header), Registries list (see display in Issuer info page in LCW)

- Issuance date: AchievementCredential.issuanceDate (https://1edtech.github.io/openbadges-specification/ob_v3p0.html#achievementcredential) (**Required** )

- Expiration date: AchievementCredential.expirationDate (https://1edtech.github.io/openbadges-specification/ob_v3p0.html#achievementcredential) - should already be displayed if there is one.

- Achievement.achievement.Type ( https://1edtech.github.io/openbadges-specification/ob_v3p0.html#achievement). This is a new field for the LCW. We can label it "Achievement Type". Example: **Achievement Type** Certificate

- Achievement.description (https://1edtech.github.io/openbadges-specification/ob_v3p0.html#achievement) (**Required** )  - already being displayed

- Achievement.criteria.narrative (https://1edtech.github.io/openbadges-specification/ob_v3p0.html#achievement) (**Required** ) - this is a markdown field that is already being displayed but the markdown doesn't get rendered. See issue #456

**Comment by kayaelle** [comment]
Some test credentials can be found here: https://github.com/jchartrand/dcc-test-creds/tree/main

We will make more and link to here.

**Comment by kayaelle** [comment]
Adding this note in reference to: [](https://github.com/digitalcredentials/learner-credential-wallet/issues/460)

AchievementCredential and OpenBadgeCredential are synonymous in the OBv3 spec. As a reference from the schema (https://purl.imsglobal.org/spec/ob/v3p0/schema/json/ob_v3p0_achievementcredential_schema.json): " "type" : {
"oneOf" : [ {
"description" : "The value of the type property MUST be an unordered set. One of the items MUST be the URI 'VerifiableCredential', and one of the items MUST be the URI 'AchievementCredential' or the URI 'OpenBadgeCredential'.",

What we should do is look for both and then display the same fields for both so that when you add the missing fields for "OpenBadgeCredential" they display for both

**Comment by bmuramatsu** [comment]
@kayaelle I recommend that the `achievement.image.id `image be both legible and the same dimensions on screen as the `issuer.image` image as in LCW.

Verified works the same in VerifierPlus on Mac Safari and Android Chrome; and on iOS and Android LCW v2.0.11-Build 66

Display on VerifierPlus
<img src="https://github.com/digitalcredentials/web-verifier-plus/assets/752326/4e4c688f-bc54-4476-9340-ba5acf9b0b36" width=30%>

Display in LCW.
<img src="https://github.com/digitalcredentials/web-verifier-plus/assets/752326/c13cc508-0648-4d42-aaf4-acf5a574453f"  width=30%>

**Comment by kayaelle** [comment]
Looks ok for 'OpenBadgeCredential'. Will create a follow-up ticket for example badges that are of type 'AchievementCredential' to test display - @jmcioffi4 please note for QA script.

Another follow ticket to consider display of VC without 'AchievementCredential' or the URI 'OpenBadgeCredential'. and how to accommodate @contexts that we can't plan for in advance.

**Comment by kayaelle** [comment]
Related to [https://github.com/digitalcredentials/learner-credential-wallet/issues/460](https://github.com/digitalcredentials/learner-credential-wallet/issues/460)
