### ISSUE TITLE
achievement.image.id image size (should be same size as issuer.image)

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/web-verifier-plus#89]
I recommend that the `achievement.image.id `image be both legible and the same dimensions on screen as the `issuer.image` image as in LCW.

Verified works the same in VerifierPlus on Mac Safari and Android Chrome; and on iOS and Android LCW v2.0.11-Build 66

**Display on VerifierPlus**
<img src="https://github.com/digitalcredentials/web-verifier-plus/assets/752326/4e4c688f-bc54-4476-9340-ba5acf9b0b36" width=30%>

**Display in LCW**
<img src="https://github.com/digitalcredentials/web-verifier-plus/assets/752326/c13cc508-0648-4d42-aaf4-acf5a574453f"  width=30%>

Tested with:
https://lcw.app/request.html?issuer=https%3A%2F%2Fissuer.example.com&vc_request_url=https://verify.dcconsortium.org/request/credential&challenge=ke12345678-0001&auth_type=bearer

(Need to use the hyperlink version to add to Android LCW to test, same as `dccrequest://request?issuer=https%3A%2F%2Fissuer.example.com&vc_request_url=https://verify.dcconsortium.org/request/credential&challenge=ke12345678-0001&auth_type=bearer`)

**Comment by bmuramatsu** [comment]
Note: the `achievement.image.id image` is the same size on "wide" windows width in desktop browsers. As the media port (window width) decreases, the image scales smaller to the size seen in the iOS screenshot in the original issue description.

**Comment by lautom36** [comment]
Fixed in this [PR](https://github.com/digitalcredentials/web-verifier-plus/pull/95).

**Comment by kayaelle** [comment]
Looks good. Closing.
