### ISSUE TITLE
Display of achievementSubject.name and achievementType on VerifierPlus

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/web-verifier-plus#90]
VerifierPlus displays `achievementSubject.name` and `achievementType` as smaller text underneath the credential name. LCW displays this information under Expiration Date.

1. I think the `achievementSubject.name` should be at least as prominent as the descriptive text of the credential. I think the name should have the same weight as the other data on the page. This would mean increasing the font size. 
2. Where these two fields are displayed should be consistent between LCW and VerifierPlus. 
3. I prefer the display of `achievementSubject.name` in LCW v2.0.11-Build 66, that is in the main body of the display, versus the current VerifierPlus implementation.
4. I prefer the `achievementType` under the credential name as I think that information is related. It could also go in the main body of the display as in LCW.

Display and relative sizing is consistent between Android Chrome and iOS Safari. Using iOS for the screenshot of VerifierPlus below.

**VerifierPlus display**
<img src="https://github.com/digitalcredentials/web-verifier-plus/assets/752326/d3b99da8-9574-436f-8369-772f91f7cc90" width=30%>

**LCW v2.0.11-Build 66 display**
<img src="https://github.com/digitalcredentials/web-verifier-plus/assets/752326/734d0598-4a66-4fa2-9873-d7bd423c1196" width=30%>

**Comment by lautom36** [comment]
[PR](https://github.com/digitalcredentials/web-verifier-plus/pull/95)

**Comment by kayaelle** [comment]
Confirmed display updates
