### ISSUE TITLE
Viewing Terms or Privacy links from a Public Link, and using the browser back button causes Runtime Errors

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/web-verifier-plus#93]
Happens in both iOS (mobile Safari) and Android (Chrome).

To reproduce in iOS:
- View a Public Link created in LCW ([example](https://verifierplus.org/credentials/6e086e76-87dc-4976-802a-bfba5422ee26))
- LCW opens browser
- Scroll to the bottom of the verified credential in the Public Link
- Select either Terms of Use or Privacy Policy
- Browser displays Terms / Privacy as expected
- Use the back button in the browser, browser returns to the same public link ([example](https://verifierplus.org/credentials/6e086e76-87dc-4976-802a-bfba5422ee26))
- Browser  reports two errors and does not display the verified credential
- Refreshing the page using the refresh button will reload and display the verified credential as expected.

**Error Messages from Chrome**
<img src="https://github.com/digitalcredentials/web-verifier-plus/assets/752326/18f9680d-945a-4a60-be5c-0872c3e09f6f" width=30%><img src="https://github.com/digitalcredentials/web-verifier-plus/assets/752326/d5d059e5-1b77-47b3-bd50-759ea1a360b0" width=30%>

**Error Messages from Mobile Safari**
<img src="https://github.com/digitalcredentials/web-verifier-plus/assets/752326/ac3dc017-3a23-46c5-b753-9e25dce9b100" width="30%"> <img src="https://github.com/digitalcredentials/web-verifier-plus/assets/752326/0e9bb604-be9b-43bb-87ab-baca7e123c28" width="30%">

**Comment by kayaelle** [comment]
This is happening in desktop browser too.

**Comment by lautom36** [comment]
Pr: [96](https://github.com/digitalcredentials/web-verifier-plus/pull/96)

**Comment by kayaelle** [comment]
Confirmed bug is fixed.
