### ISSUE TITLE
Display specific registry in Verification section of a credential on VerifierPlus

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/web-verifier-plus#94]
We should display the actual registry if it's known in the verification section on VerifierPlus.

Currently, on VerifierPlus, when a credential is verified, if the issuer is in a recognized registry Verifier Plus displays "DCC Trust Registry" for all recognized registries.

<img src="https://github.com/digitalcredentials/web-verifier-plus/assets/752326/dad8f1b6-0fdd-4e34-ada1-637592560871" width=30%>

**Comment by lautom36** [comment]
[pr](https://github.com/digitalcredentials/web-verifier-plus/pull/107)

**Comment by kayaelle** [comment]
It appears that the issuer name is being displayed instead of the registry name. 



![Image](https://github.com/digitalcredentials/web-verifier-plus/assets/206059/a5063564-4926-4ee1-9fd1-c5e66dd9a066)



![Image](https://github.com/digitalcredentials/web-verifier-plus/assets/206059/afd3a56c-b1d4-429d-95ec-5819a6b818bd)

**Comment by lautom36** [comment]
Oops sorry, can you send me that credential? I think I have it fixed but I want to check with another credential to be sure.

**Comment by kayaelle** [comment]
Hey @lautom36 - you can find example credentials here: https://github.com/digitalcredentials/docs/tree/main/example-credentials

You can create your own here: https://issuer.dcconsortium.org/ui

**Comment by lautom36** [comment]
The latest changes are on this [pr](https://github.com/digitalcredentials/web-verifier-plus/pull/107)

**Comment by alexfigtree** [comment]
Tested in latest version - registry is now being displayed - closing this ticket.

**Comment by alexfigtree** [comment]
Keeping open until after deployment

**Comment by alexfigtree** [comment]
Deployed on 3/18/24.
