### ISSUE TITLE
Display issues especially with Subject Name on Public Links

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/web-verifier-plus#98]
In version 98c0a2a 0.1.0 of VerifierPlus, there are display issues for the Subject Name field.

1. Subject Name should be styled as other fields Issuer, Issuance Date, Criteria
2. There may be excess space between Subject Name and Issuance Date
3. We may want to add the Description label back in for clarity, the display read ok without it prior to adding in Subject Name where it is located. It may have also been removed accidentally.

<img src="https://github.com/digitalcredentials/web-verifier-plus/assets/752326/eff383bd-87d2-431c-996d-b7d4105e2693" width=30%>

**Comment by lautom36** [comment]
Below is what the verification page like after changes 1 and 2. Would you like me to add the Description label back?

<img width="406" alt="Screenshot 2023-09-28 at 3 21 25 PM" src="https://github.com/digitalcredentials/web-verifier-plus/assets/72038363/f68c9ce4-7c1e-417a-9474-f8cc30e50383">

**Comment by kayaelle** [comment]
@bmuramatsu - I think we should add the description label back. What do you think?

**Comment by kayaelle** [comment]
@lautom36 - when testing https://github.com/digitalcredentials/web-verifier-plus/issues/104 I see that the description field has been added.

**Comment by kayaelle** [comment]
Description field is set to display.

**Comment by alexfigtree** [comment]
Description is being displayed with space issues fixed. Closing this ticket.



![Image](https://github.com/digitalcredentials/web-verifier-plus/assets/3487193/6d8c37ae-5414-4c54-9c11-50900ad3567e)

**Comment by alexfigtree** [comment]
Keeping open until after deployment

**Comment by alexfigtree** [comment]
Deployed on 3/18/24.
